import { Role, RolePermissions } from '@/types/auth'

export const ROLE_LABELS: Record<Role, string> = {
  dg: 'Director General',
  director_ops: 'Director Operations',
  inspector: 'Inspector',
  analyst: 'Analyst',
  viewer: 'Viewer',
}

export const ROLE_PERMISSIONS: Record<Role, RolePermissions> = {
  dg: {
    canViewDashboard: true,
    canManageFarms: true,
    canAddFarms: true,
    canDeleteFarms: true,
    canManageLicenses: true,
    canApproveLicenses: true,
    canManageInspections: true,
    canScheduleInspections: true,
    canViewReports: true,
    canExportData: true,
    canManageUsers: true,
    canManageSettings: true,
    canChangeStatus: true,
  },
  director_ops: {
    canViewDashboard: true,
    canManageFarms: true,
    canAddFarms: true,
    canDeleteFarms: false,
    canManageLicenses: true,
    canApproveLicenses: true,
    canManageInspections: true,
    canScheduleInspections: true,
    canViewReports: true,
    canExportData: true,
    canManageUsers: false,
    canManageSettings: false,
    canChangeStatus: true,
  },
  inspector: {
    canViewDashboard: true,
    canManageFarms: false,
    canAddFarms: false,
    canDeleteFarms: false,
    canManageLicenses: false,
    canApproveLicenses: false,
    canManageInspections: true,
    canScheduleInspections: true,
    canViewReports: true,
    canExportData: false,
    canManageUsers: false,
    canManageSettings: false,
    canChangeStatus: false,
  },
  analyst: {
    canViewDashboard: true,
    canManageFarms: false,
    canAddFarms: false,
    canDeleteFarms: false,
    canManageLicenses: false,
    canApproveLicenses: false,
    canManageInspections: false,
    canScheduleInspections: false,
    canViewReports: true,
    canExportData: true,
    canManageUsers: false,
    canManageSettings: false,
    canChangeStatus: false,
  },
  viewer: {
    canViewDashboard: true,
    canManageFarms: false,
    canAddFarms: false,
    canDeleteFarms: false,
    canManageLicenses: false,
    canApproveLicenses: false,
    canManageInspections: false,
    canScheduleInspections: false,
    canViewReports: true,
    canExportData: false,
    canManageUsers: false,
    canManageSettings: false,
    canChangeStatus: false,
  },
}
